nginx:
    build: ./nginx/
    ports:
        - 80:80
    links:
        - php
    volumes:
        - .:/var/www/html

db:
    image: postgres
    hostname: db
    environment:
        POSTGRES_PASSWORD: dbpass
        POSTGRES_USER: dbuser
        POSTGRES_DB: db
    container_name: db_container

php:
    build: .
    expose:
        - 9000
    links:
        - db
    environment:
        DB_HOST: db
        DB_NAME: db
        DB_USER: dbuser
        DB_PASSWORD: dbpass
    volumes:
        - .:/var/www/html
    container_name: php_container
