nginx:
    build: ./nginx/
    ports:
        - 80:80
    links:
        - php
    volumes:
        - .:/var/www/html

db:
    image: postgres:9.3
    hostname: db
    environment:
        POSTGRES_PASSWORD: $DB_PASSWORD
        POSTGRES_USER: $DB_USER
        POSTGRES_DB: $DB_NAME
    container_name: db_container

php:
    build: .
    expose:
        - 9000
    links:
        - db
    environment:
        DB_HOST: db
        DB_NAME: $DB_NAME
        DB_USER: $DB_USER
        DB_PASSWORD: $DB_PASSWORD
        LOG_THRESHOLD: 2
        CI_ENV: development
    volumes:
        - .:/var/www/html
    container_name: php_container
